// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drpumftlxtmzoxlirpqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRycHVtZnRseHRtem94bGlycHFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5MTE3MDksImV4cCI6MjA1NjQ4NzcwOX0.w73ExMKY_0Ntgdzg93GpzMs5sJ_wThbL1qwYBmCqrY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);